POST http://localhost:3220/api/user/register  HTTP/1.1
content-type: application/json

{
    "name": "ikram",
    "password": "ikram",
    "role": "seller"
    
}

###

POST http://localhost:3220/api/user/login  HTTP/1.1
content-type: application/json

{
    "name": "ikram",
    "password": "ikram"
}
###


GET http://localhost:3220/api/user/getAllUsers  HTTP/1.1
content-type: application/json

###

PUT http://localhost:3220/api/user/updateUser/62921bdeef3dadd88dc2217e  HTTP/1.1
content-type: application/json
Authorization: Baerer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJVc2VySW5mbyI6eyJuYW1lIjoibWFqZWVkIiwicm9sZSI6ImJ1eWVyIn0sImlhdCI6MTY1Mzc1MzkwNSwiZXhwIjozMzA3ODY3ODEwLCJpc3MiOiJhZGVkYXlvYWRlZ2JveWUifQ.FSavN66jcTr5fYRJ6y52rdiYx4hR-1-gR6Yjd2ucCdA
{
    "role": "seller"
}

###


GET http://localhost:3220/api/user/findUser/6291c8ff8e320335982536b5  HTTP/1.1
content-type: application/json
Authorization: Baerer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoibWFyeWFtIiwiaWF0IjoxNjUzNzIxMzYzLCJleHAiOjMzMDc4MDI3MjYsImlzcyI6ImFkZWRheW9hZGVnYm95ZSJ9.IwxRCNnFW54I64f37vtw-EMvbpgEh9lT8NafYjq1Nr4

###

DELETE http://localhost:3220/api/user/deleteUser/6291c8ff8e320335982536b5  HTTP/1.1
content-type: application/json
Authorization: Baerer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoibWFyeWFtIiwiaWF0IjoxNjUzNzIxMzYzLCJleHAiOjMzMDc4MDI3MjYsImlzcyI6ImFkZWRheW9hZGVnYm95ZSJ9.IwxRCNnFW54I64f37vtw-EMvbpgEh9lT8NafYjq1Nr4

###


PUT http://localhost:3220/api/transact/deposit/62921bdeef3dadd88dc2217e  HTTP/1.1
content-type: application/json
Authorization: Baerer eeyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJVc2VySW5mbyI6eyJuYW1lIjoibWFqZWVkIiwicm9sZSI6ImJ1eWVyIn0sImlhdCI6MTY1Mzc1MzkwNSwiZXhwIjozMzA3ODY3ODEwLCJpc3MiOiJhZGVkYXlvYWRlZ2JveWUifQ.FSavN66jcTr5fYRJ6y52rdiYx4hR-1-gR6Yjd2ucCdA
{
    "deposit": 100
}

###

POST http://localhost:3220/api/product/addProduct  HTTP/1.1
content-type: application/json
Authorization: Baerer 

{
    "productName": "yeah bread",
    "cost": 0.99,
    "amountAvailable": 23,
    "sellerId": "629246e09ed26f3132bf8aec"
}

###


POST http://localhost:3220/api/transact/buyProduct/6291c8ff8e320335982536b5  HTTP/1.1
content-type: application/json
Authorization: Baerer 


{
    "productId": "6291eefe3b306bcc00389bbe",
    "quantity": 5
}

###


GET http://localhost:3220/api/product/getAllProduct  HTTP/1.1
content-type: application/json


###